// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v6.31.1
// source: meshtastic/interdevice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Version of the interdevice protocol spoken on the link. Both sides send
// theirs in the ping/pong handshake; a peer reporting a different one runs
// firmware that does not match and is not talked to.
//
// On a change that breaks the other side (renumbered fields, changed
// semantics, removed messages), raise the value of CURRENT. Do not add
// another entry: this enum carries a single constant, not a history.
type InterdeviceVersion int32

const (
	InterdeviceVersion_INTERDEVICE_VERSION_UNSPECIFIED InterdeviceVersion = 0
	// Never use 1: ping/pong were bools before the handshake existed, and a
	// bool true is the same varint on the wire as the number 1, so firmware
	// predating the handshake would pass it.
	InterdeviceVersion_INTERDEVICE_VERSION_CURRENT InterdeviceVersion = 2
)

// Enum value maps for InterdeviceVersion.
var (
	InterdeviceVersion_name = map[int32]string{
		0: "INTERDEVICE_VERSION_UNSPECIFIED",
		2: "INTERDEVICE_VERSION_CURRENT",
	}
	InterdeviceVersion_value = map[string]int32{
		"INTERDEVICE_VERSION_UNSPECIFIED": 0,
		"INTERDEVICE_VERSION_CURRENT":     2,
	}
)

func (x InterdeviceVersion) Enum() *InterdeviceVersion {
	p := new(InterdeviceVersion)
	*p = x
	return p
}

func (x InterdeviceVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterdeviceVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[0].Descriptor()
}

func (InterdeviceVersion) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[0]
}

func (x InterdeviceVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterdeviceVersion.Descriptor instead.
func (InterdeviceVersion) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{0}
}

// Defines the supported file operations
type FileOperation int32

const (
	FileOperation_GET    FileOperation = 0
	FileOperation_POST   FileOperation = 1
	FileOperation_PUT    FileOperation = 2
	FileOperation_DELETE FileOperation = 3
)

// Enum value maps for FileOperation.
var (
	FileOperation_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
	}
	FileOperation_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
	}
)

func (x FileOperation) Enum() *FileOperation {
	p := new(FileOperation)
	*p = x
	return p
}

func (x FileOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[1].Descriptor()
}

func (FileOperation) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[1]
}

func (x FileOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileOperation.Descriptor instead.
func (FileOperation) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{1}
}

// Outcome of a file or directory operation. The requester must be able to
// tell a transient condition from a definitive one: BUSY is worth another
// try, NOT_FOUND is not.
type FileStatus int32

const (
	FileStatus_FILE_UNSPECIFIED FileStatus = 0
	FileStatus_FILE_OK          FileStatus = 1
	// Retry later: the co-processor is doing card maintenance (mount,
	// free space scan) and cannot serve the request right now
	FileStatus_FILE_BUSY      FileStatus = 2
	FileStatus_FILE_NO_CARD   FileStatus = 3
	FileStatus_FILE_NOT_FOUND FileStatus = 4
	// PUT only: offset did not match the current end of the file. file_size
	// carries the size the file actually has, so the writer can resync (or
	// recognize its own chunk as already written after a lost response).
	FileStatus_FILE_OFFSET_CONFLICT FileStatus = 5
	FileStatus_FILE_IO_ERROR        FileStatus = 6
	FileStatus_FILE_NOT_A_FILE      FileStatus = 7 // path is a directory (GET) or not one (listing)
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_UNSPECIFIED",
		1: "FILE_OK",
		2: "FILE_BUSY",
		3: "FILE_NO_CARD",
		4: "FILE_NOT_FOUND",
		5: "FILE_OFFSET_CONFLICT",
		6: "FILE_IO_ERROR",
		7: "FILE_NOT_A_FILE",
	}
	FileStatus_value = map[string]int32{
		"FILE_UNSPECIFIED":     0,
		"FILE_OK":              1,
		"FILE_BUSY":            2,
		"FILE_NO_CARD":         3,
		"FILE_NOT_FOUND":       4,
		"FILE_OFFSET_CONFLICT": 5,
		"FILE_IO_ERROR":        6,
		"FILE_NOT_A_FILE":      7,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[2].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[2]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{2}
}

// What to do with the SD card of the co-processor
type SdCommand int32

const (
	SdCommand_SD_COMMAND_UNSPECIFIED SdCommand = 0
	SdCommand_SD_MOUNT               SdCommand = 1 // mount a card that is in the slot, also after an eject
	SdCommand_SD_EJECT               SdCommand = 2 // flush and release the card so it can be pulled safely
	SdCommand_SD_FORMAT              SdCommand = 3 // wipe the card and put a fresh FAT on it, then mount it
)

// Enum value maps for SdCommand.
var (
	SdCommand_name = map[int32]string{
		0: "SD_COMMAND_UNSPECIFIED",
		1: "SD_MOUNT",
		2: "SD_EJECT",
		3: "SD_FORMAT",
	}
	SdCommand_value = map[string]int32{
		"SD_COMMAND_UNSPECIFIED": 0,
		"SD_MOUNT":               1,
		"SD_EJECT":               2,
		"SD_FORMAT":              3,
	}
)

func (x SdCommand) Enum() *SdCommand {
	p := new(SdCommand)
	*p = x
	return p
}

func (x SdCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[3].Descriptor()
}

func (SdCommand) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[3]
}

func (x SdCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdCommand.Descriptor instead.
func (SdCommand) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{3}
}

type SdCardInfo_CardType int32

const (
	SdCardInfo_NONE         SdCardInfo_CardType = 0
	SdCardInfo_MMC          SdCardInfo_CardType = 1
	SdCardInfo_SD           SdCardInfo_CardType = 2
	SdCardInfo_SDHC         SdCardInfo_CardType = 3
	SdCardInfo_SDXC         SdCardInfo_CardType = 4
	SdCardInfo_UNKNOWN_CARD SdCardInfo_CardType = 5
)

// Enum value maps for SdCardInfo_CardType.
var (
	SdCardInfo_CardType_name = map[int32]string{
		0: "NONE",
		1: "MMC",
		2: "SD",
		3: "SDHC",
		4: "SDXC",
		5: "UNKNOWN_CARD",
	}
	SdCardInfo_CardType_value = map[string]int32{
		"NONE":         0,
		"MMC":          1,
		"SD":           2,
		"SDHC":         3,
		"SDXC":         4,
		"UNKNOWN_CARD": 5,
	}
)

func (x SdCardInfo_CardType) Enum() *SdCardInfo_CardType {
	p := new(SdCardInfo_CardType)
	*p = x
	return p
}

func (x SdCardInfo_CardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdCardInfo_CardType) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[4].Descriptor()
}

func (SdCardInfo_CardType) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[4]
}

func (x SdCardInfo_CardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdCardInfo_CardType.Descriptor instead.
func (SdCardInfo_CardType) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{3, 0}
}

type SdCardInfo_FatType int32

const (
	SdCardInfo_UNKNOWN_FAT SdCardInfo_FatType = 0
	SdCardInfo_FAT16       SdCardInfo_FatType = 1
	SdCardInfo_FAT32       SdCardInfo_FatType = 2
	SdCardInfo_EXFAT       SdCardInfo_FatType = 3
)

// Enum value maps for SdCardInfo_FatType.
var (
	SdCardInfo_FatType_name = map[int32]string{
		0: "UNKNOWN_FAT",
		1: "FAT16",
		2: "FAT32",
		3: "EXFAT",
	}
	SdCardInfo_FatType_value = map[string]int32{
		"UNKNOWN_FAT": 0,
		"FAT16":       1,
		"FAT32":       2,
		"EXFAT":       3,
	}
)

func (x SdCardInfo_FatType) Enum() *SdCardInfo_FatType {
	p := new(SdCardInfo_FatType)
	*p = x
	return p
}

func (x SdCardInfo_FatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdCardInfo_FatType) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[5].Descriptor()
}

func (SdCardInfo_FatType) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[5]
}

func (x SdCardInfo_FatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdCardInfo_FatType.Descriptor instead.
func (SdCardInfo_FatType) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{3, 1}
}

type I2CResult_Status int32

const (
	// Never sent: an all-defaults (e.g. accidentally empty) message must
	// not decode as a successful transaction
	I2CResult_UNSPECIFIED  I2CResult_Status = 0
	I2CResult_OK           I2CResult_Status = 1
	I2CResult_NACK_ADDRESS I2CResult_Status = 2
	I2CResult_NACK_DATA    I2CResult_Status = 3
	I2CResult_ERROR        I2CResult_Status = 4
)

// Enum value maps for I2CResult_Status.
var (
	I2CResult_Status_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "OK",
		2: "NACK_ADDRESS",
		3: "NACK_DATA",
		4: "ERROR",
	}
	I2CResult_Status_value = map[string]int32{
		"UNSPECIFIED":  0,
		"OK":           1,
		"NACK_ADDRESS": 2,
		"NACK_DATA":    3,
		"ERROR":        4,
	}
)

func (x I2CResult_Status) Enum() *I2CResult_Status {
	p := new(I2CResult_Status)
	*p = x
	return p
}

func (x I2CResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (I2CResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[6].Descriptor()
}

func (I2CResult_Status) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[6]
}

func (x I2CResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use I2CResult_Status.Descriptor instead.
func (I2CResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{4, 0}
}

// Message for file operations
type FileTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation FileOperation `protobuf:"varint,1,opt,name=operation,proto3,enum=meshtastic.FileOperation" json:"operation,omitempty"` // File operation (GET, POST, PUT, DELETE)
	Filepath  string        `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`                                  // Path of the file on the SD card
	Filedata  []byte        `protobuf:"bytes,3,opt,name=filedata,proto3" json:"filedata,omitempty"`                                  // Chunk content (POST/PUT request, GET response)
	Status    FileStatus    `protobuf:"varint,4,opt,name=status,proto3,enum=meshtastic.FileStatus" json:"status,omitempty"`          // Response: outcome of the operation
	Message   string        `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                    // Response: human readable detail, may be empty
	Offset    uint64        `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`                                     // Byte offset of this chunk within the file (ranged GET/PUT)
	// GET request: number of bytes to read, 0 = max chunk size. A response
	// carries at most the filedata max_size (see interdevice.options) per
	// chunk; larger requests are truncated, visible in the filedata length.
	Length   uint32 `protobuf:"varint,7,opt,name=length,proto3" json:"length,omitempty"`
	FileSize uint64 `protobuf:"varint,8,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"` // GET response: total size of the file
}

func (x *FileTransfer) Reset() {
	*x = FileTransfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_interdevice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransfer) ProtoMessage() {}

func (x *FileTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransfer.ProtoReflect.Descriptor instead.
func (*FileTransfer) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{0}
}

func (x *FileTransfer) GetOperation() FileOperation {
	if x != nil {
		return x.Operation
	}
	return FileOperation_GET
}

func (x *FileTransfer) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *FileTransfer) GetFiledata() []byte {
	if x != nil {
		return x.Filedata
	}
	return nil
}

func (x *FileTransfer) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_UNSPECIFIED
}

func (x *FileTransfer) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileTransfer) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileTransfer) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FileTransfer) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

// Message for structured directory listing
type DirectoryListing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Directory string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"` // Path of the directory
	// One page of entry names, full FAT LFN length. Subdirectories carry a
	// trailing slash. Note that a name whose directory prefix pushes the
	// combined path past the FileTransfer.filepath limit cannot round-trip.
	// Page size is the max_count in interdevice.options; page through with
	// offset and total_count.
	Filenames  []string   `protobuf:"bytes,2,rep,name=filenames,proto3" json:"filenames,omitempty"`
	Status     FileStatus `protobuf:"varint,3,opt,name=status,proto3,enum=meshtastic.FileStatus" json:"status,omitempty"` // Response: outcome of the operation
	Message    string     `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                           // Response: human readable detail, may be empty
	Offset     uint32     `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`                            // Request: skip this many entries (paging)
	TotalCount uint32     `protobuf:"varint,6,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`  // Response: total number of entries in the directory
}

func (x *DirectoryListing) Reset() {
	*x = DirectoryListing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_interdevice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectoryListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryListing) ProtoMessage() {}

func (x *DirectoryListing) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryListing.ProtoReflect.Descriptor instead.
func (*DirectoryListing) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{1}
}

func (x *DirectoryListing) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *DirectoryListing) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

func (x *DirectoryListing) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_UNSPECIFIED
}

func (x *DirectoryListing) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DirectoryListing) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DirectoryListing) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// A single I2C transaction: an optional write followed by an optional
// read with repeated start, matching the TwoWire usage of sensor drivers
// (beginTransmission/write.../endTransmission(false)/requestFrom)
type I2CTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   uint32 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`                     // 7-bit device address
	WriteData []byte `protobuf:"bytes,2,opt,name=write_data,json=writeData,proto3" json:"write_data,omitempty"` // Bytes to write, may be empty
	// Number of bytes to read after the write, 0 = write-only. Bounded by
	// the read_data max_size of I2CResult (see interdevice.options); larger
	// requests are truncated, visible in the returned byte count.
	ReadLen uint32 `protobuf:"varint,3,opt,name=read_len,json=readLen,proto3" json:"read_len,omitempty"`
}

func (x *I2CTransaction) Reset() {
	*x = I2CTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_interdevice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *I2CTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CTransaction) ProtoMessage() {}

func (x *I2CTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CTransaction.ProtoReflect.Descriptor instead.
func (*I2CTransaction) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{2}
}

func (x *I2CTransaction) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *I2CTransaction) GetWriteData() []byte {
	if x != nil {
		return x.WriteData
	}
	return nil
}

func (x *I2CTransaction) GetReadLen() uint32 {
	if x != nil {
		return x.ReadLen
	}
	return 0
}

// SD card statistics
type SdCardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Card initialized and usable. False while `busy` is set does not mean
	// there is no card: the co-processor does not know yet.
	Present   bool                `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	CardType  SdCardInfo_CardType `protobuf:"varint,2,opt,name=card_type,json=cardType,proto3,enum=meshtastic.SdCardInfo_CardType" json:"card_type,omitempty"`
	FatType   SdCardInfo_FatType  `protobuf:"varint,3,opt,name=fat_type,json=fatType,proto3,enum=meshtastic.SdCardInfo_FatType" json:"fat_type,omitempty"`
	CardSize  uint64              `protobuf:"varint,4,opt,name=card_size,json=cardSize,proto3" json:"card_size,omitempty"`    // Filesystem size in bytes
	UsedBytes uint64              `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"` // Used bytes (may be expensive to compute on FAT32)
	FreeBytes uint64              `protobuf:"varint,6,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"` // Free bytes
	// used_bytes/free_bytes are only meaningful when true: the scan behind
	// them runs in the background after mount and can take a while, and a
	// full card is otherwise indistinguishable from a scan in progress
	StatsValid bool `protobuf:"varint,7,opt,name=stats_valid,json=statsValid,proto3" json:"stats_valid,omitempty"`
	// The co-processor is mounting a card right now, so whether one is
	// present is not decided yet. Ask again rather than concluding the slot
	// is empty.
	Busy bool `protobuf:"varint,8,opt,name=busy,proto3" json:"busy,omitempty"`
	// A card answers in the slot but carries no filesystem that could be
	// mounted (present is false then). Formatting it makes it usable.
	Unformatted bool `protobuf:"varint,9,opt,name=unformatted,proto3" json:"unformatted,omitempty"`
}

func (x *SdCardInfo) Reset() {
	*x = SdCardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_interdevice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SdCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdCardInfo) ProtoMessage() {}

func (x *SdCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdCardInfo.ProtoReflect.Descriptor instead.
func (*SdCardInfo) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{3}
}

func (x *SdCardInfo) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *SdCardInfo) GetCardType() SdCardInfo_CardType {
	if x != nil {
		return x.CardType
	}
	return SdCardInfo_NONE
}

func (x *SdCardInfo) GetFatType() SdCardInfo_FatType {
	if x != nil {
		return x.FatType
	}
	return SdCardInfo_UNKNOWN_FAT
}

func (x *SdCardInfo) GetCardSize() uint64 {
	if x != nil {
		return x.CardSize
	}
	return 0
}

func (x *SdCardInfo) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *SdCardInfo) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *SdCardInfo) GetStatsValid() bool {
	if x != nil {
		return x.StatsValid
	}
	return false
}

func (x *SdCardInfo) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

func (x *SdCardInfo) GetUnformatted() bool {
	if x != nil {
		return x.Unformatted
	}
	return false
}

// Result of an I2CTransaction
type I2CResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   I2CResult_Status `protobuf:"varint,1,opt,name=status,proto3,enum=meshtastic.I2CResult_Status" json:"status,omitempty"`
	ReadData []byte           `protobuf:"bytes,2,opt,name=read_data,json=readData,proto3" json:"read_data,omitempty"` // Data read from the device, empty for write-only transactions
}

func (x *I2CResult) Reset() {
	*x = I2CResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_interdevice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *I2CResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CResult) ProtoMessage() {}

func (x *I2CResult) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CResult.ProtoReflect.Descriptor instead.
func (*I2CResult) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{4}
}

func (x *I2CResult) GetStatus() I2CResult_Status {
	if x != nil {
		return x.Status
	}
	return I2CResult_UNSPECIFIED
}

func (x *I2CResult) GetReadData() []byte {
	if x != nil {
		return x.ReadData
	}
	return nil
}

// Main message for interdevice communication
type InterdeviceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Correlates a response with its request: responses echo the id of the
	// request they answer. 0 for unsolicited messages (e.g. the nmea stream).
	Id uint32 `protobuf:"varint,15,opt,name=id,proto3" json:"id,omitempty"`
	// The message data
	//
	// Types that are assignable to Data:
	//
	//	*InterdeviceMessage_Nmea
	//	*InterdeviceMessage_Beep
	//	*InterdeviceMessage_I2CTransaction
	//	*InterdeviceMessage_I2CResult
	//	*InterdeviceMessage_I2CScan
	//	*InterdeviceMessage_I2CScanResult
	//	*InterdeviceMessage_FileTransfer
	//	*InterdeviceMessage_DirectoryListing
	//	*InterdeviceMessage_GetSdInfo
	//	*InterdeviceMessage_SdInfo_
	//	*InterdeviceMessage_Ping
	//	*InterdeviceMessage_Pong
	//	*InterdeviceMessage_Nack
	//	*InterdeviceMessage_SdCommand
	Data isInterdeviceMessage_Data `protobuf_oneof:"data"`
}

func (x *InterdeviceMessage) Reset() {
	*x = InterdeviceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_interdevice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterdeviceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterdeviceMessage) ProtoMessage() {}

func (x *InterdeviceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterdeviceMessage.ProtoReflect.Descriptor instead.
func (*InterdeviceMessage) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{5}
}

func (x *InterdeviceMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (m *InterdeviceMessage) GetData() isInterdeviceMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *InterdeviceMessage) GetNmea() string {
	if x, ok := x.GetData().(*InterdeviceMessage_Nmea); ok {
		return x.Nmea
	}
	return ""
}

func (x *InterdeviceMessage) GetBeep() uint32 {
	if x, ok := x.GetData().(*InterdeviceMessage_Beep); ok {
		return x.Beep
	}
	return 0
}

func (x *InterdeviceMessage) GetI2CTransaction() *I2CTransaction {
	if x, ok := x.GetData().(*InterdeviceMessage_I2CTransaction); ok {
		return x.I2CTransaction
	}
	return nil
}

func (x *InterdeviceMessage) GetI2CResult() *I2CResult {
	if x, ok := x.GetData().(*InterdeviceMessage_I2CResult); ok {
		return x.I2CResult
	}
	return nil
}

func (x *InterdeviceMessage) GetI2CScan() bool {
	if x, ok := x.GetData().(*InterdeviceMessage_I2CScan); ok {
		return x.I2CScan
	}
	return false
}

func (x *InterdeviceMessage) GetI2CScanResult() []byte {
	if x, ok := x.GetData().(*InterdeviceMessage_I2CScanResult); ok {
		return x.I2CScanResult
	}
	return nil
}

func (x *InterdeviceMessage) GetFileTransfer() *FileTransfer {
	if x, ok := x.GetData().(*InterdeviceMessage_FileTransfer); ok {
		return x.FileTransfer
	}
	return nil
}

func (x *InterdeviceMessage) GetDirectoryListing() *DirectoryListing {
	if x, ok := x.GetData().(*InterdeviceMessage_DirectoryListing); ok {
		return x.DirectoryListing
	}
	return nil
}

func (x *InterdeviceMessage) GetGetSdInfo() bool {
	if x, ok := x.GetData().(*InterdeviceMessage_GetSdInfo); ok {
		return x.GetSdInfo
	}
	return false
}

func (x *InterdeviceMessage) GetSdInfo_() *SdCardInfo {
	if x, ok := x.GetData().(*InterdeviceMessage_SdInfo_); ok {
		return x.SdInfo_
	}
	return nil
}

func (x *InterdeviceMessage) GetPing() InterdeviceVersion {
	if x, ok := x.GetData().(*InterdeviceMessage_Ping); ok {
		return x.Ping
	}
	return InterdeviceVersion_INTERDEVICE_VERSION_UNSPECIFIED
}

func (x *InterdeviceMessage) GetPong() InterdeviceVersion {
	if x, ok := x.GetData().(*InterdeviceMessage_Pong); ok {
		return x.Pong
	}
	return InterdeviceVersion_INTERDEVICE_VERSION_UNSPECIFIED
}

func (x *InterdeviceMessage) GetNack() bool {
	if x, ok := x.GetData().(*InterdeviceMessage_Nack); ok {
		return x.Nack
	}
	return false
}

func (x *InterdeviceMessage) GetSdCommand() SdCommand {
	if x, ok := x.GetData().(*InterdeviceMessage_SdCommand); ok {
		return x.SdCommand
	}
	return SdCommand_SD_COMMAND_UNSPECIFIED
}

type isInterdeviceMessage_Data interface {
	isInterdeviceMessage_Data()
}

type InterdeviceMessage_Nmea struct {
	Nmea string `protobuf:"bytes,1,opt,name=nmea,proto3,oneof"`
}

type InterdeviceMessage_Beep struct {
	Beep uint32 `protobuf:"varint,2,opt,name=beep,proto3,oneof"`
}

type InterdeviceMessage_I2CTransaction struct {
	I2CTransaction *I2CTransaction `protobuf:"bytes,3,opt,name=i2c_transaction,json=i2cTransaction,proto3,oneof"`
}

type InterdeviceMessage_I2CResult struct {
	I2CResult *I2CResult `protobuf:"bytes,4,opt,name=i2c_result,json=i2cResult,proto3,oneof"`
}

type InterdeviceMessage_I2CScan struct {
	I2CScan bool `protobuf:"varint,5,opt,name=i2c_scan,json=i2cScan,proto3,oneof"` // Request: scan the secondary I2C bus
}

type InterdeviceMessage_I2CScanResult struct {
	I2CScanResult []byte `protobuf:"bytes,6,opt,name=i2c_scan_result,json=i2cScanResult,proto3,oneof"` // Response: 7-bit addresses of discovered devices
}

type InterdeviceMessage_FileTransfer struct {
	FileTransfer *FileTransfer `protobuf:"bytes,7,opt,name=file_transfer,json=fileTransfer,proto3,oneof"`
}

type InterdeviceMessage_DirectoryListing struct {
	DirectoryListing *DirectoryListing `protobuf:"bytes,8,opt,name=directory_listing,json=directoryListing,proto3,oneof"`
}

type InterdeviceMessage_GetSdInfo struct {
	GetSdInfo bool `protobuf:"varint,9,opt,name=get_sd_info,json=getSdInfo,proto3,oneof"` // Request: SD card statistics
}

type InterdeviceMessage_SdInfo_ struct {
	SdInfo_ *SdCardInfo `protobuf:"bytes,10,opt,name=sd_info,json=sdInfo,proto3,oneof"` // Response
}

type InterdeviceMessage_Ping struct {
	// Link liveness probe and version handshake. The receiver answers ping
	// with pong, echoing the id. Touches no peripherals, so it works with
	// nothing attached. Both carry the version the sender speaks; a peer
	// that answers with a different one speaks another protocol and must
	// not be used.
	Ping InterdeviceVersion `protobuf:"varint,11,opt,name=ping,proto3,enum=meshtastic.InterdeviceVersion,oneof"`
}

type InterdeviceMessage_Pong struct {
	Pong InterdeviceVersion `protobuf:"varint,12,opt,name=pong,proto3,enum=meshtastic.InterdeviceVersion,oneof"`
}

type InterdeviceMessage_Nack struct {
	// Response: the request could not be decoded or is of an unhandled
	// type, so the requester fails fast instead of burning its timeout.
	// Echoes the id when known, 0 when the frame was undecodable. Never
	// sent in reaction to a nack.
	Nack bool `protobuf:"varint,13,opt,name=nack,proto3,oneof"`
}

type InterdeviceMessage_SdCommand struct {
	// Request: mount the card, or release it so it can be pulled safely. The
	// co-processor answers with sd_info. Without an eject the card is mounted
	// on its own and kept mounted; after one it stays released until a mount
	// is asked for.
	SdCommand SdCommand `protobuf:"varint,14,opt,name=sd_command,json=sdCommand,proto3,enum=meshtastic.SdCommand,oneof"`
}

func (*InterdeviceMessage_Nmea) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_Beep) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_I2CTransaction) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_I2CResult) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_I2CScan) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_I2CScanResult) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_FileTransfer) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_DirectoryListing) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_GetSdInfo) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_SdInfo_) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_Ping) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_Pong) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_Nack) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_SdCommand) isInterdeviceMessage_Data() {}

var File_meshtastic_interdevice_proto protoreflect.FileDescriptor

var file_meshtastic_interdevice_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x22, 0x96, 0x02, 0x0a, 0x0c, 0x46,
	0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0xd1, 0x01, 0x0a, 0x10, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69,
	0x63, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x64, 0x0a, 0x0e, 0x49, 0x32, 0x43, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x77, 0x72, 0x69, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x4c, 0x65, 0x6e, 0x22, 0xdb, 0x03,
	0x0a, 0x0a, 0x53, 0x64, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x53, 0x64, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x61, 0x72, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x66, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73,
	0x74, 0x69, 0x63, 0x2e, 0x53, 0x64, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x46,
	0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x66, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x63, 0x61, 0x72, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x73, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x66,
	0x72, 0x65, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x66, 0x72, 0x65, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x75, 0x73, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x75, 0x73, 0x79, 0x12,
	0x20, 0x0a, 0x0b, 0x75, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x75, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65,
	0x64, 0x22, 0x4b, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x4d, 0x43, 0x10, 0x01,
	0x12, 0x06, 0x0a, 0x02, 0x53, 0x44, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x44, 0x48, 0x43,
	0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x44, 0x58, 0x43, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10, 0x05, 0x22, 0x3b,
	0x0a, 0x07, 0x46, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x46, 0x41, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x41,
	0x54, 0x31, 0x36, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x41, 0x54, 0x33, 0x32, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x45, 0x58, 0x46, 0x41, 0x54, 0x10, 0x03, 0x22, 0xad, 0x01, 0x0a, 0x09,
	0x49, 0x32, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x49, 0x32, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4d, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0c, 0x4e, 0x41, 0x43, 0x4b, 0x5f, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x41, 0x43, 0x4b, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x03,
	0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x22, 0xbb, 0x05, 0x0a, 0x12,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x6d, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x6e, 0x6d, 0x65, 0x61, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x65, 0x65, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x62, 0x65, 0x65, 0x70, 0x12, 0x45,
	0x0a, 0x0f, 0x69, 0x32, 0x63, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61,
	0x73, 0x74, 0x69, 0x63, 0x2e, 0x49, 0x32, 0x43, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x69, 0x32, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x0a, 0x69, 0x32, 0x63, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x49, 0x32, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x48, 0x00, 0x52, 0x09, 0x69, 0x32, 0x63, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a,
	0x08, 0x69, 0x32, 0x63, 0x5f, 0x73, 0x63, 0x61, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x07, 0x69, 0x32, 0x63, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x32,
	0x63, 0x5f, 0x73, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0d, 0x69, 0x32, 0x63, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x3f, 0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65,
	0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x11, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x00,
	0x52, 0x10, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x64, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x67, 0x65, 0x74, 0x53, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x07, 0x73, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74,
	0x69, 0x63, 0x2e, 0x53, 0x64, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52,
	0x06, 0x73, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74,
	0x69, 0x63, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x34, 0x0a,
	0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6d, 0x65,
	0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x70,
	0x6f, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x63, 0x6b, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x63, 0x6b, 0x12, 0x36, 0x0a, 0x0a, 0x73, 0x64, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x53, 0x64, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x09, 0x73, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x5a, 0x0a, 0x12, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x23, 0x0a, 0x1f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x56,
	0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x44, 0x45, 0x56,
	0x49, 0x43, 0x45, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x55, 0x52, 0x52,
	0x45, 0x4e, 0x54, 0x10, 0x02, 0x2a, 0x37, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x55, 0x54,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x2a, 0xa6,
	0x01, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x10, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x42, 0x55, 0x53, 0x59, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10,
	0x03, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f,
	0x55, 0x4e, 0x44, 0x10, 0x04, 0x12, 0x18, 0x0a, 0x14, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4f, 0x46,
	0x46, 0x53, 0x45, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x4c, 0x49, 0x43, 0x54, 0x10, 0x05, 0x12,
	0x11, 0x0a, 0x0d, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x49, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41,
	0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x07, 0x2a, 0x52, 0x0a, 0x09, 0x53, 0x64, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x44, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x41,
	0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x53, 0x44, 0x5f, 0x4d, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x53, 0x44, 0x5f, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x44, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x10, 0x03, 0x42, 0x67, 0x0a, 0x14, 0x6f,
	0x72, 0x67, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x42, 0x11, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x67, 0x6f,
	0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0xaa, 0x02, 0x14, 0x4d, 0x65, 0x73,
	0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x73, 0xba, 0x02, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meshtastic_interdevice_proto_rawDescOnce sync.Once
	file_meshtastic_interdevice_proto_rawDescData = file_meshtastic_interdevice_proto_rawDesc
)

func file_meshtastic_interdevice_proto_rawDescGZIP() []byte {
	file_meshtastic_interdevice_proto_rawDescOnce.Do(func() {
		file_meshtastic_interdevice_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshtastic_interdevice_proto_rawDescData)
	})
	return file_meshtastic_interdevice_proto_rawDescData
}

var file_meshtastic_interdevice_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_meshtastic_interdevice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_meshtastic_interdevice_proto_goTypes = []interface{}{
	(InterdeviceVersion)(0),    // 0: meshtastic.InterdeviceVersion
	(FileOperation)(0),         // 1: meshtastic.FileOperation
	(FileStatus)(0),            // 2: meshtastic.FileStatus
	(SdCommand)(0),             // 3: meshtastic.SdCommand
	(SdCardInfo_CardType)(0),   // 4: meshtastic.SdCardInfo.CardType
	(SdCardInfo_FatType)(0),    // 5: meshtastic.SdCardInfo.FatType
	(I2CResult_Status)(0),      // 6: meshtastic.I2CResult.Status
	(*FileTransfer)(nil),       // 7: meshtastic.FileTransfer
	(*DirectoryListing)(nil),   // 8: meshtastic.DirectoryListing
	(*I2CTransaction)(nil),     // 9: meshtastic.I2CTransaction
	(*SdCardInfo)(nil),         // 10: meshtastic.SdCardInfo
	(*I2CResult)(nil),          // 11: meshtastic.I2CResult
	(*InterdeviceMessage)(nil), // 12: meshtastic.InterdeviceMessage
}
var file_meshtastic_interdevice_proto_depIdxs = []int32{
	1,  // 0: meshtastic.FileTransfer.operation:type_name -> meshtastic.FileOperation
	2,  // 1: meshtastic.FileTransfer.status:type_name -> meshtastic.FileStatus
	2,  // 2: meshtastic.DirectoryListing.status:type_name -> meshtastic.FileStatus
	4,  // 3: meshtastic.SdCardInfo.card_type:type_name -> meshtastic.SdCardInfo.CardType
	5,  // 4: meshtastic.SdCardInfo.fat_type:type_name -> meshtastic.SdCardInfo.FatType
	6,  // 5: meshtastic.I2CResult.status:type_name -> meshtastic.I2CResult.Status
	9,  // 6: meshtastic.InterdeviceMessage.i2c_transaction:type_name -> meshtastic.I2CTransaction
	11, // 7: meshtastic.InterdeviceMessage.i2c_result:type_name -> meshtastic.I2CResult
	7,  // 8: meshtastic.InterdeviceMessage.file_transfer:type_name -> meshtastic.FileTransfer
	8,  // 9: meshtastic.InterdeviceMessage.directory_listing:type_name -> meshtastic.DirectoryListing
	10, // 10: meshtastic.InterdeviceMessage.sd_info:type_name -> meshtastic.SdCardInfo
	0,  // 11: meshtastic.InterdeviceMessage.ping:type_name -> meshtastic.InterdeviceVersion
	0,  // 12: meshtastic.InterdeviceMessage.pong:type_name -> meshtastic.InterdeviceVersion
	3,  // 13: meshtastic.InterdeviceMessage.sd_command:type_name -> meshtastic.SdCommand
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_meshtastic_interdevice_proto_init() }
func file_meshtastic_interdevice_proto_init() {
	if File_meshtastic_interdevice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshtastic_interdevice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileTransfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshtastic_interdevice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectoryListing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshtastic_interdevice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*I2CTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshtastic_interdevice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SdCardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshtastic_interdevice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*I2CResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshtastic_interdevice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterdeviceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_meshtastic_interdevice_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*InterdeviceMessage_Nmea)(nil),
		(*InterdeviceMessage_Beep)(nil),
		(*InterdeviceMessage_I2CTransaction)(nil),
		(*InterdeviceMessage_I2CResult)(nil),
		(*InterdeviceMessage_I2CScan)(nil),
		(*InterdeviceMessage_I2CScanResult)(nil),
		(*InterdeviceMessage_FileTransfer)(nil),
		(*InterdeviceMessage_DirectoryListing)(nil),
		(*InterdeviceMessage_GetSdInfo)(nil),
		(*InterdeviceMessage_SdInfo_)(nil),
		(*InterdeviceMessage_Ping)(nil),
		(*InterdeviceMessage_Pong)(nil),
		(*InterdeviceMessage_Nack)(nil),
		(*InterdeviceMessage_SdCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshtastic_interdevice_proto_rawDesc,
			NumEnums:      7,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_interdevice_proto_goTypes,
		DependencyIndexes: file_meshtastic_interdevice_proto_depIdxs,
		EnumInfos:         file_meshtastic_interdevice_proto_enumTypes,
		MessageInfos:      file_meshtastic_interdevice_proto_msgTypes,
	}.Build()
	File_meshtastic_interdevice_proto = out.File
	file_meshtastic_interdevice_proto_rawDesc = nil
	file_meshtastic_interdevice_proto_goTypes = nil
	file_meshtastic_interdevice_proto_depIdxs = nil
}
