// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v6.31.1
// source: meshtastic/serial_hal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SerialHalCommand_Type int32

const (
	SerialHalCommand_UNSET            SerialHalCommand_Type = 0
	SerialHalCommand_PIN_MODE         SerialHalCommand_Type = 1
	SerialHalCommand_DIGITAL_WRITE    SerialHalCommand_Type = 2
	SerialHalCommand_DIGITAL_READ     SerialHalCommand_Type = 3
	SerialHalCommand_ATTACH_INTERRUPT SerialHalCommand_Type = 4
	SerialHalCommand_DETACH_INTERRUPT SerialHalCommand_Type = 5
	SerialHalCommand_SPI_TRANSFER     SerialHalCommand_Type = 6
	SerialHalCommand_NOOP             SerialHalCommand_Type = 7
)

// Enum value maps for SerialHalCommand_Type.
var (
	SerialHalCommand_Type_name = map[int32]string{
		0: "UNSET",
		1: "PIN_MODE",
		2: "DIGITAL_WRITE",
		3: "DIGITAL_READ",
		4: "ATTACH_INTERRUPT",
		5: "DETACH_INTERRUPT",
		6: "SPI_TRANSFER",
		7: "NOOP",
	}
	SerialHalCommand_Type_value = map[string]int32{
		"UNSET":            0,
		"PIN_MODE":         1,
		"DIGITAL_WRITE":    2,
		"DIGITAL_READ":     3,
		"ATTACH_INTERRUPT": 4,
		"DETACH_INTERRUPT": 5,
		"SPI_TRANSFER":     6,
		"NOOP":             7,
	}
)

func (x SerialHalCommand_Type) Enum() *SerialHalCommand_Type {
	p := new(SerialHalCommand_Type)
	*p = x
	return p
}

func (x SerialHalCommand_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerialHalCommand_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_serial_hal_proto_enumTypes[0].Descriptor()
}

func (SerialHalCommand_Type) Type() protoreflect.EnumType {
	return &file_meshtastic_serial_hal_proto_enumTypes[0]
}

func (x SerialHalCommand_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerialHalCommand_Type.Descriptor instead.
func (SerialHalCommand_Type) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_serial_hal_proto_rawDescGZIP(), []int{0, 0}
}

type SerialHalResponse_Result int32

const (
	SerialHalResponse_OK          SerialHalResponse_Result = 0
	SerialHalResponse_ERROR       SerialHalResponse_Result = 1
	SerialHalResponse_BAD_REQUEST SerialHalResponse_Result = 2
	SerialHalResponse_UNSUPPORTED SerialHalResponse_Result = 3
)

// Enum value maps for SerialHalResponse_Result.
var (
	SerialHalResponse_Result_name = map[int32]string{
		0: "OK",
		1: "ERROR",
		2: "BAD_REQUEST",
		3: "UNSUPPORTED",
	}
	SerialHalResponse_Result_value = map[string]int32{
		"OK":          0,
		"ERROR":       1,
		"BAD_REQUEST": 2,
		"UNSUPPORTED": 3,
	}
)

func (x SerialHalResponse_Result) Enum() *SerialHalResponse_Result {
	p := new(SerialHalResponse_Result)
	*p = x
	return p
}

func (x SerialHalResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerialHalResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_serial_hal_proto_enumTypes[1].Descriptor()
}

func (SerialHalResponse_Result) Type() protoreflect.EnumType {
	return &file_meshtastic_serial_hal_proto_enumTypes[1]
}

func (x SerialHalResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerialHalResponse_Result.Descriptor instead.
func (SerialHalResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_serial_hal_proto_rawDescGZIP(), []int{1, 0}
}

type SerialHalCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Host-assigned request id. Replies echo this id back in
	// SerialHalResponse.transaction_id.
	TransactionId uint32                `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Type          SerialHalCommand_Type `protobuf:"varint,2,opt,name=type,proto3,enum=meshtastic.SerialHalCommand_Type" json:"type,omitempty"`
	Pin           uint32                `protobuf:"varint,3,opt,name=pin,proto3" json:"pin,omitempty"`
	Value         uint32                `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Mode          uint32                `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Data          []byte                `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SerialHalCommand) Reset() {
	*x = SerialHalCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_serial_hal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerialHalCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialHalCommand) ProtoMessage() {}

func (x *SerialHalCommand) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_serial_hal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialHalCommand.ProtoReflect.Descriptor instead.
func (*SerialHalCommand) Descriptor() ([]byte, []int) {
	return file_meshtastic_serial_hal_proto_rawDescGZIP(), []int{0}
}

func (x *SerialHalCommand) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *SerialHalCommand) GetType() SerialHalCommand_Type {
	if x != nil {
		return x.Type
	}
	return SerialHalCommand_UNSET
}

func (x *SerialHalCommand) GetPin() uint32 {
	if x != nil {
		return x.Pin
	}
	return 0
}

func (x *SerialHalCommand) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SerialHalCommand) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *SerialHalCommand) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SerialHalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Matches the originating SerialHalCommand.transaction_id for normal
	// request/response traffic.
	//
	// A value of 0 indicates an unsolicited interrupt notification generated by
	// the device. In that case, the host should interpret value as the GPIO pin
	// that triggered.
	TransactionId uint32                   `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Result        SerialHalResponse_Result `protobuf:"varint,2,opt,name=result,proto3,enum=meshtastic.SerialHalResponse_Result" json:"result,omitempty"`
	// Used by DIGITAL_READ replies and interrupt notifications. For interrupt
	// notifications (transaction_id == 0), this carries the pin number.
	Value uint32 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Data  []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Error string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SerialHalResponse) Reset() {
	*x = SerialHalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_serial_hal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerialHalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialHalResponse) ProtoMessage() {}

func (x *SerialHalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_serial_hal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialHalResponse.ProtoReflect.Descriptor instead.
func (*SerialHalResponse) Descriptor() ([]byte, []int) {
	return file_meshtastic_serial_hal_proto_rawDescGZIP(), []int{1}
}

func (x *SerialHalResponse) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *SerialHalResponse) GetResult() SerialHalResponse_Result {
	if x != nil {
		return x.Result
	}
	return SerialHalResponse_OK
}

func (x *SerialHalResponse) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SerialHalResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SerialHalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_meshtastic_serial_hal_proto protoreflect.FileDescriptor

var file_meshtastic_serial_hal_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x73, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x5f, 0x68, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d,
	0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x22, 0xcf, 0x02, 0x0a, 0x10, 0x53, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x48, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x25,
	0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63,
	0x2e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x48, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8c, 0x01, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x50, 0x49, 0x4e, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x10, 0x01, 0x12, 0x11,
	0x0a, 0x0d, 0x44, 0x49, 0x47, 0x49, 0x54, 0x41, 0x4c, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x49, 0x47, 0x49, 0x54, 0x41, 0x4c, 0x5f, 0x52, 0x45, 0x41,
	0x44, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x54, 0x54, 0x41, 0x43, 0x48, 0x5f, 0x49, 0x4e,
	0x54, 0x45, 0x52, 0x52, 0x55, 0x50, 0x54, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x45, 0x54,
	0x41, 0x43, 0x48, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x52, 0x55, 0x50, 0x54, 0x10, 0x05, 0x12,
	0x10, 0x0a, 0x0c, 0x53, 0x50, 0x49, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x10,
	0x06, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4f, 0x50, 0x10, 0x07, 0x22, 0xf7, 0x01, 0x0a, 0x11,
	0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x48, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74,
	0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x48, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3d, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52,
	0x54, 0x45, 0x44, 0x10, 0x03, 0x42, 0x5f, 0x0a, 0x14, 0x6f, 0x72, 0x67, 0x2e, 0x6d, 0x65, 0x73,
	0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x09, 0x53,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x48, 0x61, 0x6c, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f,
	0x67, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0xaa, 0x02, 0x14, 0x4d,
	0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x73, 0xba, 0x02, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meshtastic_serial_hal_proto_rawDescOnce sync.Once
	file_meshtastic_serial_hal_proto_rawDescData = file_meshtastic_serial_hal_proto_rawDesc
)

func file_meshtastic_serial_hal_proto_rawDescGZIP() []byte {
	file_meshtastic_serial_hal_proto_rawDescOnce.Do(func() {
		file_meshtastic_serial_hal_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshtastic_serial_hal_proto_rawDescData)
	})
	return file_meshtastic_serial_hal_proto_rawDescData
}

var file_meshtastic_serial_hal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_meshtastic_serial_hal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meshtastic_serial_hal_proto_goTypes = []interface{}{
	(SerialHalCommand_Type)(0),    // 0: meshtastic.SerialHalCommand.Type
	(SerialHalResponse_Result)(0), // 1: meshtastic.SerialHalResponse.Result
	(*SerialHalCommand)(nil),      // 2: meshtastic.SerialHalCommand
	(*SerialHalResponse)(nil),     // 3: meshtastic.SerialHalResponse
}
var file_meshtastic_serial_hal_proto_depIdxs = []int32{
	0, // 0: meshtastic.SerialHalCommand.type:type_name -> meshtastic.SerialHalCommand.Type
	1, // 1: meshtastic.SerialHalResponse.result:type_name -> meshtastic.SerialHalResponse.Result
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meshtastic_serial_hal_proto_init() }
func file_meshtastic_serial_hal_proto_init() {
	if File_meshtastic_serial_hal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshtastic_serial_hal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerialHalCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshtastic_serial_hal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerialHalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshtastic_serial_hal_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_serial_hal_proto_goTypes,
		DependencyIndexes: file_meshtastic_serial_hal_proto_depIdxs,
		EnumInfos:         file_meshtastic_serial_hal_proto_enumTypes,
		MessageInfos:      file_meshtastic_serial_hal_proto_msgTypes,
	}.Build()
	File_meshtastic_serial_hal_proto = out.File
	file_meshtastic_serial_hal_proto_rawDesc = nil
	file_meshtastic_serial_hal_proto_goTypes = nil
	file_meshtastic_serial_hal_proto_depIdxs = nil
}
