// Code generated by gen/update_protos.go - DO NOT EDIT.

package proto

import (
	"fmt"
	"time"
)

const ProtobufDirty = false
const ProtobufSha = "da60cee584c6dc1efbb4a3809b98666505179b85"
const ProtobufTimestamp = int64(1781736076)
const ProtobufVersion = "v2.7.26"

func ProtobufTime() time.Time {
	return time.Unix(ProtobufTimestamp, 0)
}
func ProtobufDisplayVersion() string {
	ver := fmt.Sprintf("%s-%s", ProtobufVersion, ProtobufSha[:8])
	if ProtobufDirty {
		ver = fmt.Sprintf("%s-dirty", ver)
	}
	return ver
}
