// Code generated by gen/update_protos.go - DO NOT EDIT.

package proto

import (
	"fmt"
	"time"
)

const ProtobufDirty = false
const ProtobufSha = "dd6c3f850a56a00cbc2cc5b93db2fd43b1a2f46a"
const ProtobufTimestamp = int64(1780016740)
const ProtobufVersion = "v2.7.24"

func ProtobufTime() time.Time {
	return time.Unix(ProtobufTimestamp, 0)
}
func ProtobufDisplayVersion() string {
	ver := fmt.Sprintf("%s-%s", ProtobufVersion, ProtobufSha[:8])
	if ProtobufDirty {
		ver = fmt.Sprintf("%s-dirty", ver)
	}
	return ver
}
