// Code generated by gen/update_protos.go - DO NOT EDIT.

package proto

import (
	"fmt"
	"time"
)

const ProtobufDirty = false
const ProtobufSha = "7b2464c9b8c1521f93852261e4123826e5b25e11"
const ProtobufTimestamp = int64(1787932487)
const ProtobufVersion = "v2.8.0"

func ProtobufTime() time.Time {
	return time.Unix(ProtobufTimestamp, 0)
}
func ProtobufDisplayVersion() string {
	ver := fmt.Sprintf("%s-%s", ProtobufVersion, ProtobufSha[:8])
	if ProtobufDirty {
		ver = fmt.Sprintf("%s-dirty", ver)
	}
	return ver
}
