// Code generated by tools/version.go - DO NOT EDIT.

package generated

import (
	"fmt"
	"time"
)

const ProtobufDirty = false
const ProtobufSha = "584f0a3a359103acf0bfce506c1b1fc32c639841"
const ProtobufTimestamp = int64(1751543899)
const ProtobufVersion = "v2.7.1"

func ProtobufTime() time.Time {
	return time.Unix(ProtobufTimestamp, 0)
}
func ProtobufDisplayVersion() string {
	ver := fmt.Sprintf("%s-%s", ProtobufVersion, ProtobufSha[:8])
	if ProtobufDirty {
		ver = fmt.Sprintf("%s-dirty", ver)
	}
	return ver
}
