// Code generated by gen/update_protos.go - DO NOT EDIT.

package generated

import (
	"fmt"
	"time"
)

const ProtobufDirty = false
const ProtobufSha = "c474fd3f49864f5f66ea3cd83c26848b8ae7cc64"
const ProtobufTimestamp = int64(1766238817)
const ProtobufVersion = "v2.7.17"

func ProtobufTime() time.Time {
	return time.Unix(ProtobufTimestamp, 0)
}
func ProtobufDisplayVersion() string {
	ver := fmt.Sprintf("%s-%s", ProtobufVersion, ProtobufSha[:8])
	if ProtobufDirty {
		ver = fmt.Sprintf("%s-dirty", ver)
	}
	return ver
}
